# Generated by Django 2.2.28 on 2026-02-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0058_auto_20210302_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuer',
            name='image_preview',
        ),
        migrations.AlterField(
            model_name='badgeinstance',
            name='recipient_identifier',
            field=models.CharField(db_index=True, max_length=384),
        ),
        migrations.CreateModel(
            name='IssuerEncryptionKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_fragment', models.CharField(max_length=50)),
                ('purpose', models.CharField(choices=[('authentication', 'Authentication'), ('assertionMethod', 'Assertion Method'), ('keyAgreement', 'Key Agreement')], max_length=50)),
                ('private_key_encrypted', models.TextField()),
                ('public_key_multibase', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='issuer.Issuer')),
            ],
        ),
    ]
