# Generated by Django 2.2.28 on 2026-03-31 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0059_auto_20260227_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_fragment', models.CharField(max_length=50)),
                ('purpose', models.CharField(default='assertionMethod', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='issuer.Issuer')),
            ],
            options={
                'unique_together': {('issuer', 'key_fragment')},
            },
        ),
        migrations.DeleteModel(
            name='IssuerEncryptionKeys',
        ),
        migrations.AddField(
            model_name='issuer',
            name='main_signing_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='issuer.IssuerKey'),
        ),
    ]
