# Generated by Django 2.2.28 on 2026-03-31 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0060_auto_20260331_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeinstance',
            name='issued_on',
        ),
        migrations.AddField(
            model_name='badgeinstance',
            name='validFrom',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
