# Generated by Django 2.2.28 on 2026-03-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0061_auto_20260331_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeinstance',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='badgeinstance',
            name='validUntil',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
